### ISSUE TITLE
Trouble adjusting the initial connection timeout down from 5 minutes

### ISSUE THREAD

**Issue by jgmpzman** [googleapis/java-storage#474] opened 2020-08-21 18:24 UTC
I am having difficulty figuring out how to set the initial connection timeout to 30 seconds. It appears that the default is 5 minutes and that is too long for our application. I've tried setting it in the HttpClientBuilder by setting the default RequestConfig with a custom RequestConfig. I also tried setting a TransportOptions on the StorageOptions builder, but neither of those options seem to change the timeout. 

#### Environment details

I am using the following google versions:
<com.google.guava.version>29.0-jre</com.google.guava.version>
<google-http-client-apache-v2.version>1.35.0</google-http-client-apache-v2.version>
<com.google.cloud.version>1.111.0</com.google.cloud.version>

OS type and version:

VM with 4 Gb of ram
CentOS
4.16.2-1.el7.elrepo.x86_64 #1 SMP Thu Apr 12 09:08:05 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

Java version:
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

#### Steps to reproduce

  1. Setup firewall rule to drop 443 traffic
  2. Try to connect to google storage

#### Code example

```            // Setup Google KeyStore
            TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            tmf.init(GoogleUtils.getCertificateTrustStore());
            SSLContext sslContext = SSLContext.getInstance("SSL");
            sslContext.init(/* keyManagers */ null, tmf.getTrustManagers(), /* secureRandom */ null);
            // Setup base httpClientBuilder
            HttpClientBuilder httpClientBuilder = ApacheHttpTransport.newDefaultHttpClientBuilder().setSSLSocketFactory(new SSLConnectionSocketFactory(sslContext));
            RequestConfig.Builder requestBuilder = RequestConfig.custom().setConnectTimeout(30000).setSocketTimeout(30000).setConnectionRequestTimeout(30000);
            httpClientBuilder.setDefaultRequestConfig(requestBuilder.build());
            // Get proxy if configured
            ProxyContainer proxy = getWebProxyIfExists();
            if (proxy.isConfigured()) {
                HttpHost proxyHostDetails = new HttpHost(proxy.host, proxy.port);
                HttpRoutePlanner httpRoutePlanner = new DefaultProxyRoutePlanner(proxyHostDetails);
                // Set base proxy
                httpClientBuilder.setRoutePlanner(httpRoutePlanner).setProxyAuthenticationStrategy(ProxyAuthenticationStrategy.INSTANCE);
                // Handle user/pass if configured
                if (proxy.hasCredentials()) {
                    CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
                    credentialsProvider.setCredentials(
                            new AuthScope(proxyHostDetails.getHostName(), proxyHostDetails.getPort()),
                            new UsernamePasswordCredentials(proxy.user, proxy.password)
                    );
                    httpClientBuilder.setDefaultCredentialsProvider(credentialsProvider);
                }
            }

            final HttpTransport httpTransport = new ApacheHttpTransport(httpClientBuilder.build());

            try (InputStream resourceAsStream = new StringInputStream(jsonFileContents)) {
                GoogleCredentials credentials;
                try {
                    credentials = GoogleCredentials.fromStream(resourceAsStream, () -> httpTransport);
                    credentials = credentials.createScoped(Collections.singleton(ACCOUNT_SCOPE));
                } catch (Exception e) {
                    throw new CloudException("Invalid Service Account credentials", e);
                }

                RetrySettings.Builder retryBuilder = RetrySettings.newBuilder()
                        .setJittered(true)
                        .setMaxAttempts(2)
                        .setInitialRetryDelay(1000L)
                        .setRetryDelayMultiplier(2.0D)
                        .setMaxRetryDelay(8000L);
                storageService = StorageOptions.newBuilder()
                        .setCredentials(credentials)
                        .setHeaderProvider(FixedHeaderProvider.create("user-agent", "my custom header";)"))                       .setTransportOptions(HttpTransportOptions.newBuilder().setReadTimeout(30000).setConnectTimeout(30000).build())
                        .setRetrySettings(retryBuilder.build())
                        .build().getService();
                Bucket bucket = storageService.get(bucketName, 
                Storage.BucketGetOption.fields(Storage.BucketField.STORAGE_CLASS));
```

#### Stack trace
```
Caused by: com.google.cloud.storage.StorageException: Error getting access token for service account: Connect to accounts.google.com:443 [accounts.google.com/172.217.212.84] failed: connect timed out
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:227) ~[observer-3.2.0.jar:na]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:404) ~[observer-3.2.0.jar:na]
	at com.google.cloud.storage.StorageImpl$4.call(StorageImpl.java:288) ~[observer-3.2.0.jar:na]
	at com.google.cloud.storage.StorageImpl$4.call(StorageImpl.java:285) ~[observer-3.2.0.jar:na]
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105) ~[observer-3.2.0.jar:na]
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76) ~[observer-3.2.0.jar:na]
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50) ~[observer-3.2.0.jar:na]
	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:284) ~[observer-3.2.0.jar:na]
	at com.business.adapters.GoogleStorageAdapter.<init>(GoogleStorageAdapter.java:142) ~[observer-3.2.0.jar:na]
	... 33 common frames omitted
Caused by: java.io.IOException: Error getting access token for service account: Connect to accounts.google.com:443 [accounts.google.com/172.217.212.84] failed: connect timed out
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:444) ~[observer-3.2.0.jar:na]
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:157) ~[observer-3.2.0.jar:na]
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:145) ~[observer-3.2.0.jar:na]
	at com.google.auth.oauth2.ServiceAccountCredentials.getRequestMetadata(ServiceAccountCredentials.java:603) ~[observer-3.2.0.jar:na]
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:91) ~[observer-3.2.0.jar:na]
	at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159) ~[observer-3.2.0.jar:na]
	at com.google.cloud.http.CensusHttpModule$CensusHttpRequestInitializer.initialize(CensusHttpModule.java:109) ~[observer-3.2.0.jar:na]
	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:88) ~[observer-3.2.0.jar:na]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:423) ~[observer-3.2.0.jar:na]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:542) ~[observer-3.2.0.jar:na]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:475) ~[observer-3.2.0.jar:na]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:592) ~[observer-3.2.0.jar:na]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:401) ~[observer-3.2.0.jar:na]
	... 40 common frames omitted
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to accounts.google.com:443 [accounts.google.com/172.217.212.84] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151) ~[observer-3.2.0.jar:na]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[observer-3.2.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[observer-3.2.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[observer-3.2.0.jar:na]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[observer-3.2.0.jar:na]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[observer-3.2.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[observer-3.2.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[observer-3.2.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[observer-3.2.0.jar:na]
	at com.google.api.client.http.apache.v2.ApacheHttpRequest.execute(ApacheHttpRequest.java:73) ~[observer-3.2.0.jar:na]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012) ~[observer-3.2.0.jar:na]
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:441) ~[observer-3.2.0.jar:na]
	... 52 common frames omitted
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_252]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_252]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_252]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_252]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_252]
	at java.net.Socket.connect(Socket.java:607) ~[na:1.8.0_252]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368) ~[observer-3.2.0.jar:na]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[observer-3.2.0.jar:na]
	... 63 common frames omitted
```

**Comment by athakor** [comment] 2020-08-31 11:56
@jgmpzman please try below way to adjust the initial connection timeout and  please let us know if it fixes your issue.
```javascript
HttpTransportOptions transportOptions = StorageOptions.getDefaultHttpTransportOptions();
transportOptions = transportOptions.toBuilder().setConnectTimeout(30000).setReadTimeout(30000)
    .build();
StorageOptions storageOptions = StorageOptions.newBuilder()
    .setRetrySettings(retrySettings())
    .setTransportOptions(transportOptions)
    .build();
Storage storage = storageOptions.getService();

private static RetrySettings retrySettings() {
return RetrySettings.newBuilder()
	.setMaxAttempts(10)
	.setMaxRetryDelay(Duration.ofMillis(30000L))
	.setTotalTimeout(Duration.ofMillis(30000L))
	.setInitialRetryDelay(Duration.ofMillis(250L))
	.setRetryDelayMultiplier(1.0)
	.setInitialRpcTimeout(Duration.ofMillis(30000L))
	.setRpcTimeoutMultiplier(1.0)
	.setMaxRpcTimeout(Duration.ofMillis(30000L))
	.build();
}
```

**Comment by jgmpzman** [comment] 2020-09-01 20:47
@athakor I tried what you mentioned and the connection is still timing out at 5 minutes. Here is the updated code...

``` 
           TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            tmf.init(GoogleUtils.getCertificateTrustStore());
            SSLContext sslContext = SSLContext.getInstance("SSL");
            sslContext.init(/* keyManagers */ null, tmf.getTrustManagers(), /* secureRandom */ null);
            // Setup base httpClientBuilder
            HttpClientBuilder httpClientBuilder = ApacheHttpTransport.newDefaultHttpClientBuilder().setSSLSocketFactory(new SSLConnectionSocketFactory(sslContext));
            // Get proxy if configured
            WebProxy.WebProxyContainer proxy = CloudWebProxy.getWebProxyIfExists(adapterConfiguration.getLogger());
            if (proxy.isConfigured()) {
                HttpHost proxyHostDetails = new HttpHost(proxy.host, proxy.port);
                HttpRoutePlanner httpRoutePlanner = new DefaultProxyRoutePlanner(proxyHostDetails);
                // Set base proxy
                httpClientBuilder.setRoutePlanner(httpRoutePlanner).setProxyAuthenticationStrategy(ProxyAuthenticationStrategy.INSTANCE);
                // Handle user/pass if configured
                if (proxy.hasCredentials()) {
                    CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
                    credentialsProvider.setCredentials(
                            new AuthScope(proxyHostDetails.getHostName(), proxyHostDetails.getPort()),
                            new UsernamePasswordCredentials(proxy.user, proxy.password)
                    );
                    httpClientBuilder.setDefaultCredentialsProvider(credentialsProvider);
                }
            }

            final HttpTransport httpTransport = new ApacheHttpTransport(httpClientBuilder.build());
            HttpTransportOptions transportOptions = StorageOptions.getDefaultHttpTransportOptions();
            transportOptions = transportOptions.toBuilder().setConnectTimeout(30000).setReadTimeout(30000).build();

            try (InputStream resourceAsStream = new StringInputStream(jsonFileContents)) {
                GoogleCredentials credentials;
                try {
                    credentials = GoogleCredentials.fromStream(resourceAsStream, () -> httpTransport);
                    credentials = credentials.createScoped(Collections.singleton(ACCOUNT_SCOPE));
                } catch (Exception e) {
                    throw new CloudException("Invalid Service Account credentials", e);
                }

                storageService = StorageOptions.newBuilder()
                        .setCredentials(credentials)
                        .setHeaderProvider(FixedHeaderProvider.create("user-agent", "my custom header"))
                        .setRetrySettings(retrySettings())
                        .setTransportOptions(transportOptions)
                        .build().getService();
                Bucket bucket = storageService.get(bucketName, Storage.BucketGetOption.fields(Storage.BucketField.STORAGE_CLASS));
```

Here is the retrySettings method, just a straight copy/paste from above.

```
    private static RetrySettings retrySettings() {
        return RetrySettings.newBuilder()
                .setMaxAttempts(10)
                .setMaxRetryDelay(Duration.ofMillis(30000L))
                .setTotalTimeout(Duration.ofMillis(30000L))
                .setInitialRetryDelay(Duration.ofMillis(250L))
                .setRetryDelayMultiplier(1.0)
                .setInitialRpcTimeout(Duration.ofMillis(30000L))
                .setRpcTimeoutMultiplier(1.0)
                .setMaxRpcTimeout(Duration.ofMillis(30000L))
                .build();
    }
```

**Comment by athakor** [comment] 2020-09-03 11:44
@jgmpzman  

**Regarding Error:**

> om.google.cloud.storage.StorageException: Error getting access token for service account

1. It looks like the storage server doesn't get access token from your request. please check the respected doc [Cloud Storage authentication API authentication](https://cloud.google.com/storage/docs/authentication#apiauth)

2. Please confirm when your requests are being routed through a proxy, you may need to ensure that the `Authorization header` containing your `credentials `is not stripped out by the proxy.

Because neither storage client nor server do anything proxy specific, I think, the root cause should be searched within the proxy.

**Comment by jgmpzman** [comment] 2020-09-03 15:38
@athakor I do not have a proxy configured for this test, so it skips that if statement and goes on with no proxy. Please note that my testing instructions state that I am purposely dropping all 443 traffic in order to simulate a timeout when contacting google. The error is pretty clear as `Caused by: java.net.SocketTimeoutException: connect timed out` The question remains, why is the google api not honoring the 30 second timeout that I set in the RetrySettings and the HttpTransport options?

**Comment by jgmpzman** [comment] 2020-09-03 17:36
@athakor 
When I comment out setting the credentials it correctly times out at 30 seconds. Is there another way that I can set the credentials?
```
                        storageService = StorageOptions.newBuilder()
                        //.setCredentials(credentials)
                        .setHeaderProvider(FixedHeaderProvider.create("user-agent", "my custom header"))
                        .setRetrySettings(retrySettings())
                        .setTransportOptions(transportOptions)
                        .build().getService();
```

**Comment by athakor** [comment] 2020-09-03 18:49
>When I comment out setting the credentials it correctly times out at 30 seconds. Is there another way that I can set the credentials?

@jgmpzman Yes, you can set the credentials via the environment variable [GOOGLE_APPLICATION_CREDENTIALS](https://github.com/googleapis/google-cloud-java#authentication) and update your code like below:

```javascript
            StorageOptions storageOptions = StorageOptions.newBuilder()
                    .setHeaderProvider(FixedHeaderProvider.create("user-agent", "my custom header"))
                    .setRetrySettings(retrySettings())
                    .setTransportOptions(transportOptions)
                    .build();
            storageService = storageOptions.getDefaultInstance().getService();
            Bucket bucket = storageService.get(BUCKET_NAME);
```

**Comment by jgmpzman** [comment] 2020-09-03 18:57
@athakor 
Thanks for the suggestion, but I cannot set the creds via an environment variable as our application needs to handle multiple credentials.

**Comment by athakor** [comment] 2020-09-03 19:33
@jgmpzman, Try to supply the JSON credentials file when building the service options, `ServiceAccountCredentials` it might help you.

```javascript
            StorageOptions storageOptions = StorageOptions.newBuilder()
                    .setCredentials(ServiceAccountCredentials.fromStream(new FileInputStream("/path/to/my/key.json")))
                    .setHeaderProvider(FixedHeaderProvider.create("user-agent", "my custom header"))
                    .setRetrySettings(retrySettings())
                    .setTransportOptions(transportOptions)
                    .build();
            storageService = storageOptions.getDefaultInstance().getService();
            Bucket bucket = storageService.get(BUCKET_NAME);
```

**Comment by jgmpzman** [comment] 2020-09-03 22:39
@athakor 
I tried that and it didn't timeout at 30 seconds. Also, unfortunately, the solution needs to work for three cases:
1. No Proxy
2. Proxy with no user/password
3. Proxy with user/password
Even if that did work it only covers one option.

**Comment by jgmpzman** [comment] 2020-09-14 15:21
@athakor Do you have any updates on this?

**Comment by athakor** [comment] 2020-09-22 13:00
@jgmpzman I installed proxy locally and test it with following example and it's working fine.

The following links can help you to work with proxy:

- https://github.com/googleapis/google-auth-library-java/blob/master/README.md#configuring-a-proxy
- https://github.com/googleapis/google-cloud-java#configuring-a-proxy

**Sample:**
```javascript
import com.google.api.client.http.HttpTransport;
import com.google.api.client.http.apache.v2.ApacheHttpTransport;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.FixedHeaderProvider;
import com.google.auth.http.HttpTransportFactory;
import com.google.auth.oauth2.GoogleCredentials;
import com.google.cloud.http.HttpTransportOptions;
import com.google.cloud.storage.Bucket;
import com.google.cloud.storage.Storage;
import com.google.cloud.storage.StorageOptions;
import org.apache.http.HttpHost;
import org.apache.http.auth.AuthScope;
import org.apache.http.auth.UsernamePasswordCredentials;
import org.apache.http.client.CredentialsProvider;
import org.apache.http.client.HttpClient;
import org.apache.http.conn.routing.HttpRoutePlanner;
import org.apache.http.impl.client.BasicCredentialsProvider;
import org.apache.http.impl.client.ProxyAuthenticationStrategy;
import org.apache.http.impl.conn.DefaultProxyRoutePlanner;
import org.threeten.bp.Duration;

import java.io.IOException;

public class ProxyExample {

    private static final String PROXY_HOST = "your-proxy-host";
    private static final Integer PROXY_PORT = 8080; //your-port
    private static final String PROXY_USER = "your-user-name";
    private static final String PROXY_PASS = "your-password";
    private static final String BUCKET_NAME = "bucket-name";

    public static void main(String[] args) throws IOException {
        HttpTransportOptions transportOptions = StorageOptions.getDefaultHttpTransportOptions();
        transportOptions = transportOptions.toBuilder().setConnectTimeout(30000).setReadTimeout(30000).build();
        StorageOptions storageOptions = StorageOptions.newBuilder()
                .setCredentials(getCredentials())
                .setTransportOptions(transportOptions)
                .setHeaderProvider(FixedHeaderProvider.create("user-agent", "my custom header"))
                .setRetrySettings(retrySettings())
                .build();
        Storage storage = storageOptions.getService();
        Bucket bucket = storage.get(BUCKET_NAME);
        System.out.println(bucket);
    }

    public static GoogleCredentials getCredentials() throws IOException {
        HttpTransportFactory httpTransportFactory = getHttpTransportFactory(
                PROXY_HOST, PROXY_PORT, PROXY_USER, PROXY_PASS
        );

        return GoogleCredentials.getApplicationDefault(httpTransportFactory);
    }

    public static HttpTransportFactory getHttpTransportFactory(String proxyHost, int proxyPort, String proxyUsername, String proxyPassword) {
        HttpHost proxyHostDetails = new HttpHost(proxyHost, proxyPort);
        HttpRoutePlanner httpRoutePlanner = new DefaultProxyRoutePlanner(proxyHostDetails);

        CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
        credentialsProvider.setCredentials(
                new AuthScope(proxyHostDetails.getHostName(), proxyHostDetails.getPort()),
                new UsernamePasswordCredentials(proxyUsername, proxyPassword)
        );

        HttpClient httpClient = ApacheHttpTransport.newDefaultHttpClientBuilder()
                .setRoutePlanner(httpRoutePlanner)
                .setProxyAuthenticationStrategy(ProxyAuthenticationStrategy.INSTANCE)
                .setDefaultCredentialsProvider(credentialsProvider)
                .build();

        final HttpTransport httpTransport = new ApacheHttpTransport(httpClient);
        return () -> httpTransport;
    }

    private static RetrySettings retrySettings() {
        return RetrySettings.newBuilder()
                .setMaxAttempts(10)
                .setMaxRetryDelay(Duration.ofMillis(30000L))
                .setTotalTimeout(Duration.ofMillis(30000L))
                .setInitialRetryDelay(Duration.ofMillis(250L))
                .setRetryDelayMultiplier(1.0)
                .setInitialRpcTimeout(Duration.ofMillis(30000L))
                .setRpcTimeoutMultiplier(1.0)
                .setMaxRpcTimeout(Duration.ofMillis(30000L))
                .build();
    }
}

```
**Output:**
`Bucket{name=bucket-name}`

**Comment by athakor** [comment] 2020-10-09 07:00
Any luck on the last comment @jgmpzman? just checking in.

**Comment by jgmpzman** [comment] 2020-10-19 18:44
@athakor I was out for a bit and put on a different priorities. I tried your example with some subtle differences because it needs to work for my use case (code below). It is still timing out at 5 minutes and not 30 seconds as desired.
```
    public static GoogleCredentials getCredentials(WebProxy proxy, String jsonFileContents) throws IOException {
        HttpTransportFactory httpTransportFactory = getHttpTransportFactory(proxy);
        try (InputStream resourceAsStream = new StringInputStream(jsonFileContents)) {
            return GoogleCredentials.fromStream(resourceAsStream, httpTransportFactory);
        }
    }

    public static HttpTransportFactory getHttpTransportFactory(WebProxy proxy) {
        HttpClientBuilder httpClientBuilder = ApacheHttpTransport.newDefaultHttpClientBuilder();
        if (proxy.isConfigured()) {
            HttpHost proxyHostDetails = new HttpHost(proxy.host, proxy.port);
            HttpRoutePlanner httpRoutePlanner = new DefaultProxyRoutePlanner(proxyHostDetails);
            if (proxy.hasCredentials()) {
                CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
                credentialsProvider.setCredentials(new AuthScope(proxyHostDetails.getHostName(), proxyHostDetails.getPort()), new UsernamePasswordCredentials(proxy.user, proxy.password));
                httpClientBuilder.setDefaultCredentialsProvider(credentialsProvider);
            }
            httpClientBuilder.setProxyAuthenticationStrategy(ProxyAuthenticationStrategy.INSTANCE).setRoutePlanner(httpRoutePlanner);
        }
        final HttpTransport httpTransport = new ApacheHttpTransport(httpClientBuilder.build());
        return () -> httpTransport;
    }

    private static RetrySettings retrySettings() {
        return RetrySettings.newBuilder()
                .setMaxAttempts(10)
                .setMaxRetryDelay(Duration.ofMillis(30000L))
                .setTotalTimeout(Duration.ofMillis(30000L))
                .setInitialRetryDelay(Duration.ofMillis(250L))
                .setRetryDelayMultiplier(1.0)
                .setInitialRpcTimeout(Duration.ofMillis(30000L))
                .setRpcTimeoutMultiplier(1.0)
                .setMaxRpcTimeout(Duration.ofMillis(30000L))
                .build();
    }
```
I think the main difference is I need to set the credentials provider using the json string, where as you use the default. Have you tried your same test with string credentials instead of default?

**Comment by frankyn** [comment] 2021-06-02 18:31
This issue is a duplicate of https://github.com/googleapis/java-storage/issues/699

**Closed by frankyn** 2021-06-02 18:31 UTC
Labels: api: storage, duplicate, status: duplicate
