### ISSUE TITLE
Unable to add lifecycle rules if the location is not specified during bucket creation

### ISSUE THREAD

**Issue by rmunna** [googleapis/java-storage#122] opened 2020-02-10 08:38 UTC
Hi,
   When I try to add the lifecycle rules to a bucket without specifying "location" attribute for the bucket, bucket creation is failing with error "invalid location constraint". Where as bucket creation works without location field if lifecycle rules are not added as part of the request. 

Used Json API with help of postman, got the same error

Request: 
```
POST /storage/v1/b?project={project} HTTP/1.1
Host: www.googleapis.com
Content-Type: application/json
Authorization: Bearer {token}

{
  "name": "ia-gcs-lifecyle-test",
  "lifecycle": {
    "rule": [
      {
        "action": {
          "type": "SetStorageClass",
          "storageClass": "COLDLINE"
        },
        "condition": {
          "age": 29
        }
      }
    ]
  }
}
```

Response: 

```
{
    "error": {
        "errors": [
            {
                "domain": "global",
                "reason": "invalid",
                "message": "Invalid location constraint \"\""
            }
        ],
        "code": 400,
        "message": "Invalid location constraint \"\""
    }
}

```
Environment details
OS type and version: Windows 10
Java version: JDK 11
sdk version: google-cloud-storage-1.7.8.0.jar

**Comment by athakor** [comment] 2020-02-10 10:03
@rmunna I have tried which you have mention but i am unbale to reproduced,below are code sample and output:

**Sample:**
```javascript  
  private static final Storage STORAGE = StorageOptions.getDefaultInstance().getService();

  public static void main(String[] args) throws ExecutionException, InterruptedException {

    String bucketName = RemoteStorageHelper.generateBucketName();
    List<BucketInfo.LifecycleRule> lifecycleRules =
        ImmutableList.of(
            new BucketInfo.LifecycleRule(
                BucketInfo.LifecycleRule.LifecycleAction.newDeleteAction(),
                BucketInfo.LifecycleRule.LifecycleCondition.newBuilder()
                    .setAge(2)
                    .setIsLive(true)
                    .build()));
    try {
      Bucket bucket =
          STORAGE.create(
              BucketInfo.newBuilder(bucketName)
                  .setStorageClass(StorageClass.COLDLINE)
                  // TODO : Tried with location and without location.
                  // .setLocation("us-central1")
                  .setLifecycleRules(lifecycleRules)
                  .build());
      System.out.println("bucket " + bucketName + " was created successfully...");
      System.out.println(bucket);
    } catch (StorageException ex) {
      throw ex;
    } finally {
      RemoteStorageHelper.forceDelete(STORAGE, bucketName, 5, TimeUnit.SECONDS);
    }
  }
```
**Output:**
```
bucket gcloud-test-bucket-temp-ee93370d-b18c-4d81-a1fd-3dfa83835bf8 was created successfully...
Bucket{name=gcloud-test-bucket-temp-ee93370d-b18c-4d81-a1fd-3dfa83835bf8}
```

**Comment by rmunna** [comment] 2020-02-17 11:55
@athakor Thanks for the reply. The issue seems to be with SetStorageClass Action.

SetStorageClass Action

`
Storage storage = GCSClientFactory.getDefaultInstance();
 List<BucketInfo.LifecycleRule> lifecycleRules = ImmutableList.of(new BucketInfo.LifecycleRule(
        BucketInfo.LifecycleRule.LifecycleAction
            .newSetStorageClassAction(StorageClass.COLDLINE),
        BucketInfo.LifecycleRule.LifecycleCondition.newBuilder().setAge(2).setIsLive(true)
            .build()));

    storage.create(BucketInfo.newBuilder(BUCKET_PREFIX + UUID.randomUUID())
        .setStorageClass(StorageClass.STANDARD)
        // TODO : Try with location and without location.
        // .setLocation("us-central1")
        .setLifecycleRules(lifecycleRules).build());
`

Exception 

`
com.google.cloud.storage.StorageException: Invalid location constraint ""
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:229)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:272)
	at com.google.cloud.storage.StorageImpl$2.call(StorageImpl.java:117)
	at com.google.cloud.storage.StorageImpl$2.call(StorageImpl.java:114)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.StorageImpl.create(StorageImpl.java:113)
	at suite.noauthrz.external.contentstore.GCSBucketTest.testBucketAddLifeCycleRules1(GCSBucketTest.java:295)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:205)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:201)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid location constraint \"\"",
    "reason" : "invalid"
  } ],
  "message" : "Invalid location constraint \"\""
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:417)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1089)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:515)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:448)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:269)
	... 95 more
`

**Comment by athakor** [comment] 2020-02-18 12:26
@rmunna Thanks for filling this issue, @frankyn It's look like a backend issue.

**Success Scenarios:**

1.Create `bucket` with `location` with `BucketInfo.LifecycleRule.LifecycleAction.newSetStorageClassAction(StorageClass.STANDARD).`

2.Create `bucket` with location with `BucketInfo.LifecycleRule.LifecycleAction.newDeleteAction().`

3.Create `bucket` without `location` with `BucketInfo.LifecycleRule.LifecycleAction.newDeleteAction().
`

**Failed Scenario:**

1.Create `bucket` without `location` with `BucketInfo.LifecycleRule.LifecycleAction.newSetStorageClassAction(StorageClass.STANDARD).
`

**Example:**

```javascript
public class StorageTest {

  private static final Storage STORAGE = StorageOptions.getDefaultInstance().getService();

  public static void main(String[] args) throws ExecutionException, InterruptedException {

    String bucketName = RemoteStorageHelper.generateBucketName();
    List<BucketInfo.LifecycleRule> lifecycleRules =
        ImmutableList.of(
            new BucketInfo.LifecycleRule(
                BucketInfo.LifecycleRule.LifecycleAction.newSetStorageClassAction(
                    StorageClass.STANDARD),
                BucketInfo.LifecycleRule.LifecycleCondition.newBuilder()
                    .setAge(2)
                    .setIsLive(false)
                    .build()));
    try {
      Bucket bucket =
          STORAGE.create(
              BucketInfo.newBuilder(bucketName)
                  .setStorageClass(StorageClass.STANDARD)
                  // TODO : Try with location and without location.
                  //.setLocation("us-central1")
                  .setLifecycleRules(lifecycleRules)
                  .build());
      System.out.println("bucket " + bucketName + " was created successfully...");
      System.out.println(bucket);
    } catch (StorageException ex) {
      ex.printStackTrace();
    } finally{
      RemoteStorageHelper.forceDelete(STORAGE, bucketName, 5, TimeUnit.SECONDS);
    }
  }
}
```

**Comment by frankyn** [comment] 2020-05-22 05:16
@jkwlui can you follow-up with OLM backend team because this looks like a service issue.

**Comment by frankyn** [comment] 2020-09-11 08:55
Following up with GCS team, and will update shortly.

**Comment by frankyn** [comment] 2020-09-12 00:54
It's a bug and working with the team to resolve it.

**Comment by frankyn** [comment] 2020-10-07 17:11
Closing out bug as fix was made and pending release.

**Closed by frankyn** 2020-10-07 17:11 UTC
Labels: api: storage, external, priority: p2, type: bug
