### ISSUE TITLE
GCS Streaming upload does not respect host in StorageOption

### ISSUE THREAD

**Issue by bijukunjummen** [googleapis/java-storage#2011] opened 2023-05-09 21:15 UTC
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/java-storage/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. Core
3. OS type and version: Linux
4. Java version: 17, 8
5.  version(s): 2.22.0

#### Steps to reproduce

  1. If Host is explicitly set in StorageOpttions, this host gets correctly used for `storage.create(`, but for streaming writes using `storage.writer(..).write(..)`, the host url ends up being `www.googleapis.com` and not the host name specified by the user.

#### Code example

```java
Storage storage = StorageOptions.newBuilder()
        .setHost("example.com")
        .setHeaderProvider(FixedHeaderProvider.create("Host", "www.googleapis.com"))
        .build().getService();
```

This works correctly with the url using the custom host provided:

```java
try(InputStream resourceAsStream = this.getClass().getResourceAsStream("/samplefile.txt")) {
    byte[] content = resourceAsStream.readAllBytes();
    storage.create(BlobInfo.newBuilder("test-bucket", "samplefile").build(), content);
}
```

whereas a streaming upload has the "www.googleapis.com" hostname and ignores the user specified host:

```java
BlobInfo build = BlobInfo.newBuilder("bucket-data", "samplefile1.txt").build();
try (WriteChannel writer = storage.writer(build)) {
    try (InputStream input = this.getClass().getResourceAsStream("/samplefile.txt")) {
        int limit;
        while ((limit = input.read(buffer)) >= 0) {
            writer.write(ByteBuffer.wrap(buffer, 0, limit));
        }
    }
}
```

Expected behavior is that the streaming upload for chunk should use the hostname specified by the user.

#### External references such as API reference guides

- ?

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by BenWhitehead** [comment] 2023-05-10 14:33
This is working as intended.

When the resumable upload session is started, GCS returns a fully qualified URL of where the bytes are to be sent. According to http spec, when a client is resolving the destination of a relative link or redirect it is only able to do so relative to the elements which are not specified by the server. In this case, since GCS is specifying a fully qualified URL the client fully respects it and does not attempt to construct one of its own.

If running on GCP and using VPC-SC using a Private Service Connect domain[1] is the correct thing to do. Both the client and GCS fully support this, and we have documentation detailing the exact option to change[2].

In general, attempting a `Host` override is a bad practice and should not be done. And, in fact is completely disallowed at the protocol level for things like gRPC.

[1] https://cloud.google.com/vpc/docs/private-service-connect
[2] https://cloud.google.com/storage/docs/request-endpoints#client-libraries

**Closed by BenWhitehead** 2023-05-10 14:33 UTC
Labels: api: storage
