### ISSUE TITLE
 Randomly Receiving com.google.cloud.storage.StorageException: Connection reset

### ISSUE THREAD

**Issue by anjali2892** [googleapis/java-storage#46] opened 2019-01-26 13:18 UTC
We randomly receiving com.google.cloud.storage.StorageException: Connection reset. in some requests when uploading and downloading file from google cloud storage.
Mainly this exception is coming: 
1.  while fetching bucket instance
2.  while creating a new ACL entry on the specified blob. 

- OS: Windows 
- Java version: 8 
- google-cloud-java version(s): 1.2.1,

#### Stacktrace
Caused by: com.google.cloud.storage.StorageException: Connection reset
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:189)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:309)
	at com.google.cloud.storage.StorageImpl$4.call(StorageImpl.java:169)
	at com.google.cloud.storage.StorageImpl$4.call(StorageImpl.java:166)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:165)
	... 19 common frames omitted
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:93)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:307)
	... 26 common frames omitted

 #### 1. code snippet
      Storage storage = StorageOptions.getDefaultInstance()
          .getService();
      // get bucket instance from storage
      Bucket bucket = storage.get(bucketName);
 #### 2. code snippet 
 // get storage instance
      Storage storage = StorageOptions.getDefaultInstance()
          .getService();
      // get bucket instance from storage
      Bucket bucket = storage.get(bucketName);
 BlobId blobId = BlobId.of(bucket.getName(), subDirectory + "/" + name);
      BlobInfo blobInfo = BlobInfo.newBuilder(blobId)
          .build();
      try (WriteChannel writer = storage.writer(blobInfo)) {
        writer.write(ByteBuffer.wrap(content, 0, content.length));
      }
 if (markPublic) {
        // mark the uploaded file as public
        Acl acl = storage.createAcl(blobId, Acl.of(Acl.User.ofAllUsers(), Acl.Role.READER));
        return "https://storage.googleapis.com/" + blobInfo.getBucket() + "/" + blobId.getName();
      }

#### Additional Information
 I have also white listed .googleapis.com and *.google.com domains. But some of the calls from SDK are calling IP address directly like https://216.58.220.10 because of that my network is restricting that call.

Is there a way so that I can configure something in Storage SDK so that it should call only those APIs which are covered with google domain. I have restrictions on my firewall so that data packets from random IP addresses should not get transferred.
Below is the attached image that shows some requests are going to google.com, while some requests are going to  IP address(google owned) directly. Requests that are going directly to IP address are throwing this exception.
![kwlvx](https://user-images.githubusercontent.com/47056927/51787627-2fac1e00-219a-11e9-9d3d-0983b69cd891.png)

Thanks!

**Comment by dmitry-fa** [comment] 2020-02-06 13:19
The origin of the problem is certainly not in this API library but on the server side.
https://issuetracker.google.com/issues/123456218  was submitted to track that.
So, I'm closing this issue.

**Closed by dmitry-fa** 2020-02-06 13:19 UTC
Labels: api: storage, type: question
