### ISSUE TITLE
Cloud Storage access details

### ISSUE THREAD

**Issue by anz000** [googleapis/java-storage#391] opened 2020-06-24 23:24 UTC
I am trying to find the logs for access to the storage bucket resources. 

I am following instructions at https://cloud.google.com/storage/docs/access-logs#delivery to prepare access.

My main goal is to find the following:
- Total bandwidth
- Bandwidth per resource
This is because I want to calculate the cost of the access to the bucket resources.

Issue:
`gsutil iam ch group:cloud-storage-analytics@google.com:legacyBucketWriter gs://example-logs-bucket`

I get a `403` when I try to set the legacy bucket writer. I am the owner of the project.

The error reads:
`AccessDeniedException: 403 user@email.com does not have storage.buckets.getIamPolicy access to the Google Cloud Storage bucket.`

I also tried to set the `legacyBucketWriter` through `iAM` setting and bucket-level setting through the Google Cloud UI, but to no avail, as I haven't seen any logs in 2 days.

I am assuming that fields like `sc_bytes` and `time_taken_micros` in the logs will lead to my ultimate goal. Let me know otherwise. If there are other alternatives, then that'd be great as well.

**Comment by frankyn** [comment] 2020-06-25 04:51
Hi @anz000,

Role: `roles/owner` does not have permission `storage.buckets.getIamPolicy`. You'll need to grant `roles/storage.admin` to `user@email.com` if bucket level permissions were manipulated after it was created it may have lost project scoped bindings similar to the following:

```
{
  "bindings": [
    {
      "members": [
        "projectEditor:gcp-project", 
        "projectOwner:gcp-project"
      ], 
      "role": "roles/storage.legacyBucketOwner"
    }, 
    {
      "members": [
        "projectViewer:gcp-project"
      ], 
      "role": "roles/storage.legacyBucketReader"
    }
  ], 
  "etag": "CAE="
}

```

You could either be selective and grant the role to specific user or make sure the bindings above are assigned to your bucket. You can confirm by running:

```
gsutil iam get gs://your-bucket-name
```

Please let me know if this doesn't answer your question.

**Comment by anz000** [comment] 2020-06-25 17:49
Thanks. The logs are generated now.

Could you provide any input on how I could find the total bandwidth and bandwidth per resource from the logs? Thanks.

**Comment by frankyn** [comment] 2020-06-25 18:24
My best understanding you'll want to use `sc_bytes` which gives you:

> The number of bytes sent in the response.

I haven't tested it for partial downloads. I can give a try though if you haven't already.
Additionally, `sc_bytes` IIUC, is not exact to the object size and instead includes all metadata sent along with the response. 

IIUC you want to download specific ranges of an object but not the entire file and log bandwidth used. Is that correct?

**Comment by anz000** [comment] 2020-06-25 22:44
Yes.

Say, we have a youTube video of 60 MB. A client can access random parts of a media file. A client (browser) starts accessing the resource (play the video), and the end user could jump around the video. Let's say, the client accesses the first 10 mins, then a 5 min in the middle and then 10 mins at the last. I'm assuming these would come up as (at least) 3 different entries in the log file. I want to know the bandwidth used up for accessing the resource in such cases.

**Comment by anz000** [comment] 2020-07-08 03:24
I ran some experiment on the bucket access using browser (end-user) and then monitor the log  for those requests. 

I loaded up a video source, and seeked at different position in the video so that there would be partial access. Whenever I seeked, a new GET request got registered on the console with the following response:

```
{
   url : xyz.com?a=p,
   status: 206,
   type: media,
   initiator: other,
   size: 4.9MB,
   time: 16.92s
}
```
Meanwhile, matching up with the logs using timestamp (and other filters), the logs output included (filtered list)

| time_micros      | cs_method | cs_uri      | sc_status | cs_bytes | sc_bytes | time_taken_micros | cs_host            | 
|------------------|-----------|-------------|-----------|----------|----------|-------------------|--------------------| 
| 1593642977551596 | GET       | xyz.com?a=p | 206       | 0        | 14680064 | 21913000          | www.googleapis.com | 
| 1593643369232119 | GET       | xyz.com?a=p | 206       | 0        | 11544204 | 7485000           | www.googleapis.com | 
| 1593643068339076 | GET       | xyz.com?a=p | 206       | 0        | 14680064 | 23907000          | www.googleapis.com | 
| 1593643049449069 | GET       | xyz.com?a=p | 206       | 0        | 16777216 | 55220000          | www.googleapis.com | 
| 1593643096669944 | GET       | xyz.com?a=p | 206       | 0        | 14680064 | 33339000          | www.googleapis.com | 
| 1593643209603449 | GET       | xyz.com?a=p | 206       | 0        | 14680064 | 94794000          | www.googleapis.com | 
| 1593643237822646 | GET       | xyz.com?a=p | 206       | 0        | 14680064 | 33239000          | www.googleapis.com | 


I had 7 different accesses on various part of the video file. 

|Access| Console Data  | Log Data (from table above) |
| ------------- | ------------- | ------------- | 
|1| 4.9 MB / 16.92s  | 14.6 MB / 21.93s |
|2| 12 MB / 50.21s  | 11.54 / 7.485s  |
|3| 4.2 MB / 18.91s  | 14.6 MB / 23.907s |
|4| 4.2 MB / 28.34s  | 16.7MB / 55.22s  |
|5| 9.0 MB / 1.5m  |  14.68 MB / 33.339s |
|6| 5.1 MB / 28.5s  |  14.68 MB / 94.794s |
|7| 4.8 MB / 2.53s  |  14.68 MB / 33.239s |


I find it's odd that the sent-request was always in a given range (10 MB+) even though the one registered on the Chrome console suggested otherwise (much less size).  Am I missing something?

**Comment by frankyn** [comment] 2021-06-15 05:00
Wow. I dropped the ball here. IIRC, GCS will read the entire object when a range is requested so this is most likely the case given the data you're seeing. 

It's possible that this might be a bug in the service though. 
Is this still an open question for you @anz000? If so, we can forward this question to the right team. 

Apologies for not getting back this in a reasonable turnaround time.

**Comment by anz000** [comment] 2021-06-15 15:03
No worries. Thanks for getting back on this.

Yeah, this is still an open question, and would help us understand our bandwidth requirements. This, in turn, will help build our cost model. Thanks.

**Comment by frankyn** [comment] 2021-06-15 15:04
On it! Thanks @anz000

**Comment by frankyn** [comment] 2021-06-15 21:06
Hi @anz000,

I checked in with the backend team and ranged reads should only return/log the bytes returned. Contact used a query to compare 206 status code response sizes and object size. The bandwidth used was smaller than the actual object size.

Have you tried using doing a cURL request to compare browser access behavior?

It's possible that times aren't aligned in this case, but based on discussion only bytes requested should be returned / used.

HTH

**Comment by frankyn** [comment] 2021-06-15 21:11
Assigning @JesseLovelace because I'll be out for a bit. Thanks Jesse!

**Comment by frankyn** [comment] 2022-01-07 22:33
No update since from Jun 15, 2021, I'm closing issue. If the issue is still occurring please reopen.

**Closed by frankyn** 2022-01-07 22:33 UTC
Labels: type: question, api: storage
